// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodosApi.Context;

#nullable disable

namespace TodosApi.Migrations
{
    [DbContext(typeof(TodosContext))]
    partial class TodosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("TodosApi.Models.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e26179c-6a70-41bc-8e78-69c6b77cb910"),
                            CreatedAt = new DateTime(2023, 7, 12, 15, 20, 40, 706, DateTimeKind.Local).AddTicks(3452),
                            IsComplete = false,
                            Task = "Lavar los platos"
                        },
                        new
                        {
                            Id = new Guid("475c9174-470c-4ce0-99b0-31e2dca51bd2"),
                            CreatedAt = new DateTime(2023, 7, 12, 15, 20, 40, 706, DateTimeKind.Local).AddTicks(3493),
                            IsComplete = true,
                            Task = "English yes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
